feat - ТЗ-14
exipse/java-shareit pull request #2
Opened 2023-05-24 13:57 UTC by exipse

2023-05-25 20:39 UTC, Donald522 requested changes
Привет!

В целом все хорошо, оставил немного комментариев по мелочи.

2023-05-25 20:39 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/dto/InputBookingDto.java
> +public class InputBookingDto {
Лучше назвать BookingRequestDto

2023-05-25 20:39 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingShortDto.java
> +    private int bookerId;
почему id это Long, а bookerId это int и примитив?

2023-05-25 20:39 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +            "where i.ownerId =?1 and b.start <?2 and b.end >?3 " +
А что если начало бронирования до start, но окончание до end?
Это не считается текущим бронированием?

2023-05-25 20:39 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    public BookingDto validateRequest(Long userId, Long bookingId, Boolean approved) {
Название validate неудачное. 
validate это что-то про проверку, а тут мы отвечаем на запрос.

2023-05-25 20:39 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if ((Objects.equals(booking.getBooker().getId(), userId)) ||
Почему это условие не перенести в запрос к БД?

2023-05-25 20:39 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        LocalDateTime timeNow = LocalDateTime.now();
В now советую всегда передавать clock. Это сильно упростит написание тестов.

2023-05-25 20:39 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/comment/mapper/CommetMapper.java
> +    Comment toCommentModel(CommentDto model);
тут параметр не model

2023-05-25 20:39 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            Comment comment = new Comment();
Маппер же есть

2023-05-28 18:46 UTC, exipse commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +            "where i.ownerId =?1 and b.start <?2 and b.end >?3 " +
если брать в условие окончание до end , то мы получим бронирования, которые уже завершены

2023-05-28 21:25 UTC, exipse commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        LocalDateTime timeNow = LocalDateTime.now();
Переделал на реализацию с добавлением clock. 
Локально все тесты проходят, а на GitHub - валятся. Пришлось откатить до обратной реализации без clock.

Все же не понял для чего нужно использовать clock и как это помогает при тестировании. В интернете не особо много удалось найти. Буду очень благодарен за ссылку на статью где об этом рассказывается🙏

2023-05-29 17:51 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        LocalDateTime timeNow = LocalDateTime.now();
Ссылку на статью дать не могу.
Но когда ты запускаешь в тесте вызов LocalDate.now(), то тебе будет возвращаться каждый раз разное время (текущее). Тебе тест придется подстраивать под это, иначе тест в какой-то момент перестанет работать.

Передавая clock в now(), можно в тестах передать такой объект clock, который будет возвращать фиксированное дату/время. Это делает тесты стабильнее и понятнее.

2023-05-29 17:51 UTC, Donald522 approved these changes
Привет!

Сейчас все хорошо.

2023-05-30 20:37 UTC, merged