тз 16
exipse/java-shareit pull request #4
Opened 2023-06-14 14:58 UTC by exipse

2023-06-15 20:29 UTC, Donald522 requested changes
Привет!

Оставил несколько замечаний

2023-06-15 20:29 UTC, Donald522 commented on .github/workflows/wait-for-it.sh
> +# Use this script to test if a given TCP host/port are available
Почему эти файлы меняются?

2023-06-15 20:29 UTC, Donald522 commented on docker-compose.yml
> +      - POSTGRES_PASSWORD=root
Из под рута лучше не ходить в базу

2023-06-15 20:29 UTC, Donald522 commented on server/pom.xml
> +			<artifactId>jakarta.validation-api</artifactId>
Зачем тут эта зависимоть?

2023-06-15 20:29 UTC, Donald522 commented on server/pom.xml
> +<!--				<artifactId>maven-surefire-plugin</artifactId>-->
Комменты удалить надо

2023-06-16 13:06 UTC, exipse commented on server/pom.xml
> +			<artifactId>jakarta.validation-api</artifactId>
когда перетаскивал проект, были проблемы с запуском приложения. Не понимал из за какой аннотации. Когда проект запустится эту забыл удалить

2023-06-16 13:09 UTC, exipse commented on docker-compose.yml
> +      - POSTGRES_PASSWORD=root
Это креды из шаблона,  по которому нам надо было разделить приложение. 
Это же среды пользователя на сервере. В пачке задал вопрос тебе, но не дождался ответа. Сокурсники тоже сказали, что не знают на какие среды заменить. Все оставляли root/root

2023-06-16 13:10 UTC, exipse commented on .github/workflows/wait-for-it.sh
> +# Use this script to test if a given TCP host/port are available
это файлы из шаблона, который я загрузил себе в проект.  Удалил их.

2023-06-16 19:50 UTC, Donald522 approved these changes

2023-06-18 19:28 UTC, merged